security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Axel
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator::class # Ajout de l'authentificateur
            logout:
                path: app_logout # Ajout de la route de logout
                target: app_login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN } # Activation des règles
        - { path: ^/profile, roles: ROLE_USER } # Activation des règles

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10